version: '3.1'
services: 
  my_cluster_kafka_1:
    image: 'confluentinc/cp-kafka'
    hostname: my_cluster_kafka_1
    container_name: my_cluster_kafka_1
    ports:
      - 9091:9091
    environment:
     - KAFKA_BROKER_ID=1
     - KAFKA_ZOOKEEPER_CONNECT=my_cluster_zoo_1:2181,my_cluster_zoo_2:2182,my_cluster_zoo_3:2183
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://my_cluster_kafka_1:9091
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
     - BOOTSTRAP_SERVERS=my_cluster_kafka_1:9091,my_cluster_kafka_2:9092,my_cluster_kafka_3:9093
     - ZOOKEEPER=my_cluster_zoo_1:2181

  my_cluster_kafka_2:
    image: 'confluentinc/cp-kafka'
    hostname: my_cluster_kafka_2
    container_name: my_cluster_kafka_2
    ports:
      - 9092:9092
    environment:
     - KAFKA_BROKER_ID=2
     - KAFKA_ZOOKEEPER_CONNECT=my_cluster_zoo_1:2181,my_cluster_zoo_2:2182,my_cluster_zoo_3:2183
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://my_cluster_kafka_2:9092
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
     - BOOTSTRAP_SERVERS=my_cluster_kafka_1:9091,my_cluster_kafka_2:9092,my_cluster_kafka_3:9093
     - ZOOKEEPER=my_cluster_zoo_1:2181


  my_cluster_kafka_3:
    image: 'confluentinc/cp-kafka'
    hostname: my_cluster_kafka_3
    container_name: my_cluster_kafka_3
    ports:
      - 9093:9093
    environment:
     - KAFKA_BROKER_ID=3
     - KAFKA_ZOOKEEPER_CONNECT=my_cluster_zoo_1:2181,my_cluster_zoo_2:2182,my_cluster_zoo_3:2183
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://my_cluster_kafka_3:9093
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
     - BOOTSTRAP_SERVERS=my_cluster_kafka_1:9091,my_cluster_kafka_2:9092,my_cluster_kafka_3:9093
     - ZOOKEEPER=my_cluster_zoo_1:2181









networks:
  default:
    name: mynet2
    external: true

