version: '3.1'

services:
  my_cluster_zoo_1:
    image: zookeeper
    restart: always
    hostname: my_cluster_zoo_1
    container_name: my_cluster_zoo_1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=my_cluster_zoo_1:2888:3888;2181 server.2=my_cluster_zoo_2:2888:3888;2182 server.3=my_cluster_zoo_3:2888:3888;2183

  my_cluster_zoo_2:
    image: zookeeper
    restart: always
    hostname: my_cluster_zoo_2
    container_name: my_cluster_zoo_2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=my_cluster_zoo_1:2888:3888;2181 server.2=my_cluster_zoo_2:2888:3888;2182 server.3=my_cluster_zoo_3:2888:3888;2183

  my_cluster_zoo_3:
    image: zookeeper
    restart: always
    hostname: my_cluster_zoo_3
    container_name: my_cluster_zoo_3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=my_cluster_zoo_1:2888:3888;2181 server.2=my_cluster_zoo_2:2888:3888;2182 server.3=my_cluster_zoo_3:2888:3888;2183


networks:
  default:
    name: mynet2
    external: true
